theme: minima
title: Bioinformatics @UT Arlington
author: Balan Ramesh and Jeff Demuth
description: >
    Bioinformatics - BIOL 5340.
header_pages:
  - group1/index.md
  - group2/index.md
  - group3/index.md
  - group4/index.md
  - group5/index.md
  - data/sample.md
